name: UpdateRestImplementationFromMaster

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1        
    - name: Nightly Merge
      uses: robotology/gh-action-nightly-merge@v1.2.0
      with:
        # Name of the stable branch
        stable_branch: 'master'
        # Name of the development branch
        development_branch: 'RestImplementation'
        # User name for git commits
        user_name: 'nkdBot'
        # User email for git commits
        user_email: 'nkdbot@nkdagility.com'
        # Environment variable containing the token to use for push
        push_token: ${{ secrets.BotToken }} 
