name: UpdateRestImplementationFromMaster

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1        
    - name: Nightly Merge
      uses: robotology/gh-action-nightly-merge@v1.2.0
      with:
        stable_branch: 'master'
        development_branch: 'RestImplementation'
        push_token: ${{ secrets.BotToken }} 
      env:
        GITHUB_TOKEN: ${{ secrets.BotToken }}
